package email

import (
	"fmt"
	"html"
	"strings"
	"time"

	"github.com/sendgrid/sendgrid-go"
	"github.com/sendgrid/sendgrid-go/helpers/mail"
)

// EmailService handles sending emails via SendGrid
type EmailService struct {
	apiKey       string
	supportEmail string
}

// NewEmailService creates a new email service instance
func NewEmailService(apiKey, supportEmail string) *EmailService {
	if supportEmail == "" {
		supportEmail = "support@israeldefensestore.com"
	}
	return &EmailService{
		apiKey:       apiKey,
		supportEmail: supportEmail,
	}
}

// SendSupportEscalationEmail sends an email to support with conversation summary
func (es *EmailService) SendSupportEscalationEmail(customerEmail, summary, fullConversation string) error {
	if es.apiKey == "" {
		return fmt.Errorf("SendGrid API key not configured")
	}

	from := mail.NewEmail("IDS Chat System", "support@israeldefensestore.com")
	to := mail.NewEmail("Support Team", es.supportEmail)
	cc := mail.NewEmail("Customer", customerEmail)

	subject := "🎫 Support Escalation - Chat Request"
	timestamp := time.Now().Format("January 2, 2006 at 3:04 PM MST")

	// Generate plain text version for fallback
	plainText := generatePlainTextEmail(customerEmail, timestamp, summary, fullConversation)

	// Generate HTML version with styling
	htmlContent := generateHTMLEmail(customerEmail, timestamp, summary, fullConversation)

	message := mail.NewSingleEmail(from, subject, to, plainText, htmlContent)

	// Add CC recipient using Personalizations
	if len(message.Personalizations) > 0 {
		message.Personalizations[0].AddCCs(cc)
	}

	client := sendgrid.NewSendClient(es.apiKey)
	response, err := client.Send(message)
	if err != nil {
		return fmt.Errorf("failed to send email: %w", err)
	}

	if response.StatusCode >= 400 {
		return fmt.Errorf("SendGrid API error: status %d, body: %s", response.StatusCode, response.Body)
	}

	return nil
}

// generatePlainTextEmail creates the plain text version of the email
func generatePlainTextEmail(customerEmail, timestamp, summary, fullConversation string) string {
	return fmt.Sprintf(`SUPPORT ESCALATION REQUEST
============================

A customer has requested support escalation from the chat system.

CUSTOMER INFORMATION
--------------------
Email: %s
Submitted: %s

AI-GENERATED SUMMARY
--------------------
%s

FULL CONVERSATION
-----------------
%s

---
This email was automatically generated by the IDS Chat System.
Please respond to the customer at their email address above.
`, customerEmail, timestamp, summary, fullConversation)
}

// generateHTMLEmail creates a styled HTML email for better readability
func generateHTMLEmail(customerEmail, timestamp, summary, fullConversation string) string {
	// Escape HTML in user content to prevent XSS
	escapedEmail := html.EscapeString(customerEmail)
	escapedSummary := html.EscapeString(summary)

	// Format the conversation with proper styling
	formattedConversation := formatConversationHTML(fullConversation)

	return fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Support Escalation Request</title>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f5f5f5; line-height: 1.6;">
    <table role="presentation" style="width: 100%%; max-width: 700px; margin: 0 auto; background-color: #ffffff; border-collapse: collapse;">
        <!-- Header -->
        <tr>
            <td style="background: linear-gradient(135deg, #1a365d 0%%, #2c5282 100%%); padding: 30px 40px; text-align: center;">
                <h1 style="margin: 0; color: #ffffff; font-size: 24px; font-weight: 600;">
                    🎫 Support Escalation Request
                </h1>
                <p style="margin: 10px 0 0 0; color: #a0aec0; font-size: 14px;">
                    A customer needs assistance from the support team
                </p>
            </td>
        </tr>

        <!-- Priority Banner -->
        <tr>
            <td style="background-color: #fef3c7; padding: 15px 40px; border-left: 4px solid #f59e0b;">
                <table role="presentation" style="width: 100%%;">
                    <tr>
                        <td style="width: 30px; vertical-align: top;">
                            <span style="font-size: 20px;">⚡</span>
                        </td>
                        <td>
                            <strong style="color: #92400e;">Action Required:</strong>
                            <span style="color: #78350f;"> Please respond to the customer inquiry below.</span>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <!-- Customer Information Card -->
        <tr>
            <td style="padding: 30px 40px 20px 40px;">
                <table role="presentation" style="width: 100%%; background-color: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;">
                    <tr>
                        <td style="padding: 20px;">
                            <h2 style="margin: 0 0 15px 0; color: #1e293b; font-size: 16px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px;">
                                📋 Customer Information
                            </h2>
                            <table role="presentation" style="width: 100%%;">
                                <tr>
                                    <td style="padding: 8px 0; color: #64748b; width: 120px;">Email:</td>
                                    <td style="padding: 8px 0;">
                                        <a href="mailto:%s" style="color: #2563eb; text-decoration: none; font-weight: 500;">%s</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding: 8px 0; color: #64748b;">Submitted:</td>
                                    <td style="padding: 8px 0; color: #334155;">%s</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <!-- AI Summary Section -->
        <tr>
            <td style="padding: 0 40px 20px 40px;">
                <table role="presentation" style="width: 100%%; background-color: #eff6ff; border-radius: 8px; border: 1px solid #bfdbfe;">
                    <tr>
                        <td style="padding: 20px;">
                            <h2 style="margin: 0 0 15px 0; color: #1e40af; font-size: 16px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px;">
                                🤖 AI-Generated Summary
                            </h2>
                            <div style="color: #1e3a5f; font-size: 15px; white-space: pre-wrap; line-height: 1.7;">%s</div>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <!-- Conversation Section -->
        <tr>
            <td style="padding: 0 40px 30px 40px;">
                <h2 style="margin: 0 0 15px 0; color: #1e293b; font-size: 16px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px;">
                    💬 Full Conversation
                </h2>
                <div style="background-color: #fafafa; border-radius: 8px; border: 1px solid #e5e7eb; padding: 20px; max-height: 500px; overflow-y: auto;">
                    %s
                </div>
            </td>
        </tr>

        <!-- Footer -->
        <tr>
            <td style="background-color: #f8fafc; padding: 25px 40px; border-top: 1px solid #e2e8f0; text-align: center;">
                <p style="margin: 0 0 10px 0; color: #64748b; font-size: 13px;">
                    This email was automatically generated by the <strong>IDS Chat System</strong>
                </p>
                <p style="margin: 0; color: #94a3b8; font-size: 12px;">
                    Israel Defense Store • Customer Support Portal
                </p>
            </td>
        </tr>
    </table>
</body>
</html>`, escapedEmail, escapedEmail, timestamp, escapedSummary, formattedConversation)
}

// formatConversationHTML formats the conversation with styled message bubbles
func formatConversationHTML(conversation string) string {
	var result strings.Builder
	lines := strings.Split(conversation, "\n")

	var currentRole string
	var currentMessage strings.Builder
	messageCount := 0

	flushMessage := func() {
		if currentMessage.Len() == 0 {
			return
		}
		messageCount++
		msg := strings.TrimSpace(currentMessage.String())
		if msg == "" {
			currentMessage.Reset()
			return
		}

		escapedMsg := html.EscapeString(msg)
		// Convert newlines to <br> for HTML
		escapedMsg = strings.ReplaceAll(escapedMsg, "\n", "<br>")

		if currentRole == "User" {
			result.WriteString(fmt.Sprintf(`
                <div style="margin-bottom: 15px;">
                    <div style="display: flex; align-items: center; margin-bottom: 5px;">
                        <span style="background-color: #3b82f6; color: white; width: 28px; height: 28px; border-radius: 50%%; display: inline-flex; align-items: center; justify-content: center; font-size: 12px; font-weight: 600; margin-right: 8px;">C</span>
                        <span style="font-weight: 600; color: #1e40af; font-size: 13px;">Customer</span>
                        <span style="color: #94a3b8; font-size: 11px; margin-left: 10px;">#%d</span>
                    </div>
                    <div style="background-color: #dbeafe; border-radius: 12px; padding: 12px 16px; margin-left: 36px; color: #1e3a8a; font-size: 14px; line-height: 1.5;">
                        %s
                    </div>
                </div>`, messageCount, escapedMsg))
		} else {
			result.WriteString(fmt.Sprintf(`
                <div style="margin-bottom: 15px;">
                    <div style="display: flex; align-items: center; margin-bottom: 5px;">
                        <span style="background-color: #10b981; color: white; width: 28px; height: 28px; border-radius: 50%%; display: inline-flex; align-items: center; justify-content: center; font-size: 12px; font-weight: 600; margin-right: 8px;">A</span>
                        <span style="font-weight: 600; color: #047857; font-size: 13px;">AI Assistant</span>
                        <span style="color: #94a3b8; font-size: 11px; margin-left: 10px;">#%d</span>
                    </div>
                    <div style="background-color: #d1fae5; border-radius: 12px; padding: 12px 16px; margin-left: 36px; color: #064e3b; font-size: 14px; line-height: 1.5;">
                        %s
                    </div>
                </div>`, messageCount, escapedMsg))
		}
		currentMessage.Reset()
	}

	for _, line := range lines {
		// Skip header lines
		if strings.HasPrefix(line, "Full Conversation:") || strings.HasPrefix(line, "===") {
			continue
		}

		// Check for message headers like "[Message 1] User:"
		if strings.HasPrefix(line, "[Message") {
			flushMessage()
			if strings.Contains(line, "User:") {
				currentRole = "User"
			} else if strings.Contains(line, "Assistant:") {
				currentRole = "Assistant"
			}
			continue
		}

		// Accumulate message content
		if currentRole != "" {
			if currentMessage.Len() > 0 {
				currentMessage.WriteString("\n")
			}
			currentMessage.WriteString(line)
		}
	}

	// Flush the last message
	flushMessage()

	if result.Len() == 0 {
		return `<p style="color: #64748b; font-style: italic;">No conversation messages found.</p>`
	}

	return result.String()
}
