version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goconst
    - gocyclo
    - dupl
  exclusions:
    paths:
      - ".*_test.go$"
    warn-unused: false
  settings:
    gocyclo:
      min-complexity: 30
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 140

issues:
  max-issues-per-linter: 50
  max-same-issues: 3